# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend/src"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - "bobesz"
    target-branch: "packages-updates"
  - package-ecosystem: "npm"
      directory: "/frontend/src"
      schedule:
        interval: "daily"
      labels:
        - "dependencies"
      assignees:
        - "bobesz"
      target-branch: "packages-updates"
