# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "javascript"
    directory: "/bakend"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - "bobesz"
    target-branch: "develop"
  - package-ecosystem: "javascript"
    directory: "/frontend"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - "bobesz"
    target-branch: "develop"
