on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
name: Dev Build
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
          java-package: jdk
          architecture: x64
      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: mvn clean test
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>gh</id><username>bobesz</username><password>\${{ secrets.GITHUB }}</password></server></servers></settings>" > ~/.m2/settings.xml
          REPO="gh::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
          mvn deploy -DaltReleaseDeploymentRepository="${REPO}" -DaltSnapshotDeploymentRepository="${REPO}"
