on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
name: Dev Build
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
          java-package: jdk
          architecture: x64
      - name: Test
        env:
          GITHUB_TOKEN: 86a52554b1d843319856f1917af8ccaf16fe2a89
        run: mvn test
      - name: Build
        env:
          GITHUB_TOKEN: 86a52554b1d843319856f1917af8ccaf16fe2a89
        run: mvn clean deploy
