on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
name: Dev Build
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
          java-package: jdk
          architecture: x64
      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: mvn clean test
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          SONATYPE_USERNAME: bobesz
          SONATYPE_PASSWORD: 395858ade0560fdd5ecc587fe88fc2de3938c742
        run:  mvn -B --settings .mvn/settings.xml deploy -Dregistry=https://maven.pkg.github.com/bobnetnetwork/cms -Dtoken=${GITHUB_TOKEN}
